import type { Counselor } from "./types";

export const counselors: Counselor[] = [
  {
    id: "amara",
    name: "Amara Okonkwo",
    credentials: "PhD · Counseling Psychologist",
    gender: "woman",
    initials: "AO",
    color: "#325343",
    specialties: ["anxiety", "exams", "firstgen", "sleep"],
    tone: "gentle",
    lgbtqAffirming: true,
    faithSensitive: true,
    bio: "Works with undergraduates navigating academic pressure, first-generation college stress, and the quiet kind of anxiety that shows up before exams.",
    approach: "Warm, structured, skills-first. You’ll leave sessions with something you can actually try that week.",
    slots: ["Tue 10:00", "Tue 14:30", "Wed 16:00", "Thu 11:00", "Fri 09:30"],
  },
  {
    id: "james",
    name: "James Adeyemi",
    credentials: "LPC · Licensed Professional Counselor",
    gender: "man",
    initials: "JA",
    color: "#1e3e2e",
    specialties: ["mood", "grief", "relationships", "sleep"],
    tone: "direct",
    lgbtqAffirming: true,
    faithSensitive: false,
    bio: "Helps students who feel stuck, low, or like they’re performing okay while privately running on empty. Also sits with grief that doesn’t have a neat timeline.",
    approach: "Direct but not harsh. Names patterns, asks hard questions, and keeps the work practical.",
    slots: ["Mon 13:00", "Tue 15:00", "Wed 11:30", "Thu 17:00", "Fri 12:00"],
  },
  {
    id: "priya",
    name: "Priya Nair",
    credentials: "LMFT · Licensed Marriage & Family Therapist",
    gender: "woman",
    initials: "PN",
    color: "#397a4a",
    specialties: ["identity", "relationships", "homesickness", "anxiety"],
    tone: "gentle",
    lgbtqAffirming: true,
    faithSensitive: false,
    bio: "Affirming space for identity questions, belonging, and the particular ache of being far from home. LGBTQ+ students are explicitly welcome.",
    approach: "Collaborative and gentle. Explores the past when it’s useful; stays in the present when it isn’t.",
    slots: ["Mon 10:30", "Wed 14:00", "Thu 09:00", "Thu 15:30", "Fri 16:00"],
  },
  {
    id: "fatima",
    name: "Fatima Bello",
    credentials: "LCSW · Licensed Clinical Social Worker",
    gender: "woman",
    initials: "FB",
    color: "#205454",
    specialties: ["exams", "anxiety", "firstgen", "mood"],
    tone: "gentle",
    lgbtqAffirming: true,
    faithSensitive: true,
    bio: "Faith-sensitive counselor who also works secularly. Specializes in high-achieving students who are exhausted, and first-gen students carrying family expectations.",
    approach: "Calm, faith-aware when you want that, never when you don’t. Strong on sleep, study stress, and self-compassion.",
    slots: ["Tue 09:00", "Tue 16:30", "Wed 13:00", "Thu 10:30", "Fri 14:00"],
  },
  {
    id: "daniel",
    name: "Daniel Chen",
    credentials: "LPC · Licensed Professional Counselor",
    gender: "man",
    initials: "DC",
    color: "#0f2a1a",
    specialties: ["relationships", "exams", "mood", "sleep"],
    tone: "direct",
    lgbtqAffirming: false,
    faithSensitive: false,
    bio: "Often chosen by students who want someone straightforward — including men who are new to counseling and not sure they “do talking.”",
    approach: "Structured, goal-oriented, short on fluff. Fine with mostly messaging if live sessions feel like too much at first.",
    slots: ["Mon 16:00", "Tue 11:00", "Wed 09:30", "Thu 14:00", "Fri 10:00"],
  },
  {
    id: "chiamaka",
    name: "Chiamaka Eze",
    credentials: "PsyD · Clinical Psychologist",
    gender: "woman",
    initials: "CE",
    color: "#564c0c",
    specialties: ["grief", "identity", "homesickness", "crisis"],
    tone: "gentle",
    lgbtqAffirming: true,
    faithSensitive: true,
    bio: "Trauma-informed. Sits with loss, identity, and the feeling of being unmoored in a new city or a new year. Not a crisis service — she will always point you to emergency care when that’s what’s needed.",
    approach: "Slow, careful, deeply affirming. You set the pace.",
    slots: ["Mon 11:00", "Wed 15:30", "Thu 13:00", "Fri 11:30"],
  },
];

export function getCounselor(id: string) {
  return counselors.find((c) => c.id === id);
}
