/** NUC-recognised universities in Nigeria (federal, state, and private). */
export const NIGERIAN_UNIVERSITIES = [
  "Adekunle Ajasin University, Akungba",
  "Adeleke University, Ede",
  "Afe Babalola University, Ado-Ekiti",
  "African University of Science and Technology, Abuja",
  "Ahmadu Bello University, Zaria",
  "Ajayi Crowther University, Oyo",
  "Akwa Ibom State University",
  "Al-Hikmah University, Ilorin",
  "Al-Qalam University, Katsina",
  "Ambrose Alli University, Ekpoma",
  "American University of Nigeria, Yola",
  "Anchor University, Lagos",
  "Arthur Jarvis University, Akpabuyo",
  "Atiba University, Oyo",
  "Augustine University, Ilara",
  "Babcock University, Ilishan-Remo",
  "Bauchi State University, Gadau",
  "Bayero University, Kano",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City",
  "Benue State University, Makurdi",
  "Bingham University, Karu",
  "Borno State University, Maiduguri",
  "Bowen University, Iwo",
  "Caleb University, Imota",
  "Chrisland University, Abeokuta",
  "Christopher University, Mowe",
  "Clifford University, Owerrinta",
  "Coal City University, Enugu",
  "Covenant University, Ota",
  "Crawford University, Igbesa",
  "Crescent University, Abeokuta",
  "Cross River University of Technology, Calabar",
  "Delta State University, Abraka",
  "Dominican University, Ibadan",
  "Ebonyi State University, Abakaliki",
  "Edo State University, Uzairue",
  "Edwin Clark University, Kiagbodo",
  "Ekiti State University, Ado-Ekiti",
  "Elizade University, Ilara-Mokin",
  "Enugu State University of Science and Technology",
  "Evangel University, Akaeze",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Health Sciences, Otukpo",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Babura",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University, Birnin Kebbi",
  "Federal University, Dutse",
  "Federal University, Dutsin-Ma",
  "Federal University, Gashua",
  "Federal University, Gusau",
  "Federal University, Kashere",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Ndufu-Alike",
  "Federal University, Otuoke",
  "Federal University, Oye-Ekiti",
  "Federal University, Wukari",
  "Fountain University, Osogbo",
  "Godfrey Okoye University, Enugu",
  "Gombe State University",
  "Gregory University, Uturu",
  "Hallmark University, Ijebu-Itele",
  "Hezekiah University, Umudi",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Igbinedion University, Okada",
  "Ignatius Ajuru University of Education, Port Harcourt",
  "Imo State University, Owerri",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Joseph Sarwuan Tarka University, Makurdi",
  "Kaduna State University",
  "Kano University of Science and Technology, Wudil",
  "Kebbi State University of Science and Technology, Aliero",
  "Kings University, Ode-Omu",
  "Kogi State University, Anyigba",
  "Kwara State University, Malete",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Lagos State University of Education, Ijanikin",
  "Lagos State University of Science and Technology, Ikorodu",
  "Lagos State University, Ojo",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Legacy University, Okija",
  "Madonna University, Okija",
  "McPherson University, Seriki Sotayo",
  "Michael and Cecilia Ibru University, Agbarha-Otor",
  "Michael Okpara University of Agriculture, Umudike",
  "Modibbo Adama University, Yola",
  "Mountain Top University, Makogi Oba",
  "Nasarawa State University, Keffi",
  "National Open University of Nigeria",
  "Niger Delta University, Wilberforce Island",
  "Nigerian Army University, Biu",
  "Nigerian Defence Academy, Kaduna",
  "Nigerian Maritime University, Okerenkoko",
  "Nnamdi Azikiwe University, Awka",
  "Northwest University, Kano",
  "Novena University, Ogume",
  "Obafemi Awolowo University, Ile-Ife",
  "Oduduwa University, Ipetumodu",
  "Olabisi Onabanjo University, Ago-Iwoye",
  "Ondo State University of Medical Sciences",
  "Ondo State University of Science and Technology, Okitipupa",
  "Osun State University, Osogbo",
  "Pan-Atlantic University, Lagos",
  "Paul University, Awka",
  "Plateau State University, Bokkos",
  "Precious Cornerstone University, Ibadan",
  "Redeemer's University, Ede",
  "Renaissance University, Enugu",
  "Rhema University, Aba",
  "Ritman University, Ikot Ekpene",
  "Rivers State University, Port Harcourt",
  "Salem University, Lokoja",
  "Skyline University Nigeria, Kano",
  "Sokoto State University",
  "Southwestern University, Okun-Owa",
  "Summit University, Offa",
  "Tai Solarin University of Education, Ijagun",
  "Tansian University, Umunya",
  "Taraba State University, Jalingo",
  "Umaru Musa Yar'adua University, Katsina",
  "University of Abuja",
  "University of Africa, Toru-Orua",
  "University of Benin",
  "University of Calabar",
  "University of Delta, Agbor",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Medical Sciences, Ondo",
  "University of Nigeria, Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Usmanu Danfodiyo University, Sokoto",
  "Veritas University, Abuja",
  "Wellspring University, Benin City",
  "Wesley University, Ondo",
  "Western Delta University, Oghara",
  "Yobe State University, Damaturu",
  "Yusuf Maitama Sule University, Kano",
] as const;

export function filterUniversities(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [...NIGERIAN_UNIVERSITIES];
  return NIGERIAN_UNIVERSITIES.filter((name) => name.toLowerCase().includes(q));
}
