/** NUC-recognised universities in Nigeria (federal, state, and private), from the NUC directories. */
export const NIGERIAN_UNIVERSITIES = [
  "Abdulfattah Durojaiye University, Abeokuta",
  "AbdulKadir Kure University, Minna",
  "Abdulrasaq Abubakar Toyin University, Ganmo",
  "Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa",
  "Abia State University, Uturu",
  "Abubakar Tafawa Balewa University, Bauchi",
  "Achievers University, Owo",
  "Adamawa State University, Mubi",
  "Adeche Momoh University, Igarra",
  "Adekunle Ajasin University, Akungba",
  "Adeleke University, Ede",
  "Adeyemi Federal University of Education, Ondo",
  "Admiralty University, Ibusa",
  "Afe Babalola University, Ado-Ekiti",
  "African Aviation and Aerospace University, Abuja",
  "African University of Economics, Abuja",
  "African University of Science and Technology, Abuja",
  "Ahmadu Bello University, Zaria",
  "Ahman Pategi University, Pategi",
  "Air Force Institute of Technology, Kaduna",
  "Ajayi Crowther University, Oyo",
  "Akwa Ibom State University, Ikot Akpaden",
  "Al-Ansar University, Maiduguri",
  "Al-Bayan University, Ankpa",
  "Al-Hikmah University, Ilorin",
  "Al-Istiqama University, Sumaila",
  "Al-Muhibbah Open University, Abuja",
  "Al-Qalam University, Katsina",
  "Aletheia University, Ago-Iwoye",
  "Alex Ekwueme Federal University, Ndufu-Alike",
  "Aliko Dangote University of Science and Technology, Wudil",
  "Alvan Ikoku Federal University of Education, Owerri",
  "Amadeus University, Amizi",
  "Amaj University, Kwali",
  "Ambrose Alli University, Ekpoma",
  "American Open University, Abeokuta",
  "American University of Nigeria, Yola",
  "Anan University, Kwall",
  "Anchor University, Lagos",
  "Arthur Jarvis University, Akpabuyo",
  "Atiba University, Oyo",
  "Augustine University, Ilara",
  "Ave Maria University, Piyanko",
  "Azione Verde University, Amaigbo",
  "Azman University, Kano",
  "Baba Ahmed University, Kano",
  "Babcock University, Ilishan-Remo",
  "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti",
  "Bauchi State University, Gadau",
  "Bayelsa Medical University, Yenagoa",
  "Bayero University, Kano",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City",
  "Benue State University of Agriculture, Science and Technology, Ihugh",
  "Benue State University, Makurdi",
  "Bingham University, Karu",
  "Borno State University, Maiduguri",
  "Bowen University, Iwo",
  "Bridget University, Mbaise",
  "British Canadian University, Obudu",
  "Caleb University, Imota",
  "Canadian University of Nigeria, Abuja",
  "Capital City University, Kano",
  "Caritas University, Enugu",
  "Chrisland University, Abeokuta",
  "Christopher University, Mowe",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "City University, Abuja",
  "Claretian University of Nigeria, Nekede",
  "Clifford University, Owerrinta",
  "Coal City University, Enugu",
  "College of Petroleum and Energy Studies, Kaduna",
  "Confluence University of Science and Technology, Osara",
  "Cosmopolitan University, Abuja",
  "Covenant University, Ota",
  "Crawford University, Igbesa",
  "Crescent University, Abeokuta",
  "Cross River University of Education and Entrepreneurship, Akamkpa",
  "Cross River University of Technology, Calabar",
  "David Nweze Umahi Federal University of Medical Sciences, Uburu",
  "Delta State University of Science and Technology, Ozoro",
  "Delta State University, Abraka",
  "Dennis Osadebay University, Asaba",
  "Dominican University, Ibadan",
  "Dominion University, Ibadan",
  "Ebonyi State University of ICT, Science and Technology, Oferekpe",
  "Ebonyi State University, Abakaliki",
  "Edo State University, Uzairue",
  "Edusoko University, Bida",
  "Edwin Clark University, Kiagbodo",
  "Ekiti State University, Ado-Ekiti",
  "Eko University of Medical and Health Sciences, Ijanikin",
  "El-Amin University, Minna",
  "Elizade University, Ilara-Mokin",
  "Elrazi Medical University, Yargaya",
  "Emmanuel Alayande University of Education, Oyo",
  "Enugu State University of Science and Technology, Enugu",
  "Eranova University, Abuja",
  "European University of Nigeria, Duboyi",
  "Euston University, Abakaliki",
  "Evangel University, Akaeze",
  "Federal University of Agriculture and Developmental Studies, Iragbiji",
  "Federal University of Agriculture and Technology, Obio-Akpa",
  "Federal University of Agriculture and Technology, Okeho",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Bassambiri",
  "Federal University of Agriculture, Mubi",
  "Federal University of Agriculture, Zuru",
  "Federal University of Allied Health Sciences, Enugu",
  "Federal University of Applied Sciences, Kachia",
  "Federal University of Education, Kontagora",
  "Federal University of Education, Pankshin",
  "Federal University of Education, Zaria",
  "Federal University of Environment and Technology, Tai",
  "Federal University of Health Science and Technology, Tsafe",
  "Federal University of Health Sciences, Azare",
  "Federal University of Health Sciences, Ila Orangun",
  "Federal University of Health Sciences, Katsina",
  "Federal University of Health Sciences, Kwale",
  "Federal University of Health Sciences, Otukpo",
  "Federal University of Medicine and Medical Sciences, Abeokuta",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Science and Technology, Epe",
  "Federal University of Science and Technology, Kabo",
  "Federal University of Technology and Environmental Studies, Iyin-Ekiti",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Babura",
  "Federal University of Technology, Ikot Abasi",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University of Transportation, Daura",
  "Federal University, Birnin Kebbi",
  "Federal University, Dutse",
  "Federal University, Dutsin-Ma",
  "Federal University, Gashua",
  "Federal University, Gusau",
  "Federal University, Kashere",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Otuoke",
  "Federal University, Oye-Ekiti",
  "Federal University, Wukari",
  "First Technical University, Ibadan",
  "Fountain University, Osogbo",
  "Franco British International University, Kaduna",
  "Gerar University of Medical Science, Imope-Ijebu",
  "Glorious Vision University, Ogwa (formerly Samuel Adegboyega University)",
  "Godday Erewa University, Sapele",
  "Godfrey Okoye University, Enugu",
  "Gombe State University of Science and Technology, Kumo",
  "Gombe State University, Gombe",
  "Greenfield University, Kaduna",
  "Greenland University, Jalingo",
  "Gregory University, Uturu",
  "Hallmark University, Ijebu-Itele",
  "Havilla University, Nde-Ikom",
  "Hensard University, Toru-Orua",
  "Hezekiah University, Umudi",
  "High Flyers University, Ikere-Ekiti",
  "Hillside University of Science and Technology, Okemisi",
  "Huda University, Gusau",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Iconic Open University, Sokoto",
  "Igbinedion University, Okada",
  "Ignatius Ajuru University of Education, Port Harcourt",
  "Imo State University, Owerri",
  "Isaac Balami University of Aeronautics and Management, Lagos",
  "James Hope University, Lagos",
  "JEFAP University, Suleja",
  "Jewel University, Gombe",
  "Jigawa State University of Medical and Allied Health Sciences, Majia",
  "Jimoh Babalola University, Ilorin",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Joseph Sarwuan Tarka University, Makurdi",
  "Kaduna State University, Kaduna",
  "Karl-Kumm University, Vom",
  "Kashim Ibrahim University, Maiduguri (formerly Borno State University)",
  "Kebbi State University of Science and Technology, Aliero",
  "Kevin Eze University, Mgbowo",
  "Khadija University, Majia",
  "Khalifa Isiyaku Rabiu University, Kano",
  "Kings University, Ode-Omu",
  "Kingsley Ozumba Mbadiwe University, Ogboko",
  "Kogi State University, Anyigba",
  "Kogi State University, Kabba",
  "KolaDaisi University, Ibadan",
  "Kwara State University of Education, Ilorin",
  "Kwara State University, Malete",
  "Kwararafa University, Wukari",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Lagos State University of Education, Ijanikin",
  "Lagos State University of Science and Technology, Ikorodu",
  "Lagos State University, Ojo",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Leadership University, Abuja",
  "Legacy University, Okija",
  "Lens University, Ilemona",
  "Lighthouse University, Evbobanosa",
  "Lux Mundi University, Umuahia",
  "Madonna University, Okija",
  "Maduka University, Ekwegbe",
  "Maranatha University, Lagos",
  "Margaret Lawrence University, Umunede",
  "Maria Assumpta University, Owerri",
  "Maryam Abacha American University of Nigeria, Kano",
  "McPherson University, Seriki Sotayo",
  "Mercy Medical University, Iwo",
  "Mewar International University, Masaka",
  "Michael and Cecilia Ibru University, Agbarha-Otor",
  "Michael Okpara University of Agriculture, Umudike",
  "Millennium Crest University, Ikare-Akoko",
  "Minaret University, Ikirun",
  "Miva Open University, Abuja",
  "Modibbo Adama University, Yola",
  "Monarch University, Iyesi-Ota",
  "Moshood Abiola University of Science and Technology, Abeokuta",
  "Mountain Top University, Makogi Oba",
  "Mudiame University, Irrua",
  "Muhammad Kamalud-Deen University, Ilorin",
  "Nasarawa State University, Keffi",
  "National Open University of Nigeria",
  "National University of Science and Technology, Abuja",
  "New City University, Ayetoro",
  "Newgate University, Minna",
  "Niger Delta University, Wilberforce Island",
  "Nigeria Police Academy, Wudil",
  "Nigerian Army University, Biu",
  "Nigerian British University, Asa",
  "Nigerian Defence Academy, Kaduna",
  "Nigerian Maritime University, Okerenkoko",
  "Nigerian University of Technology and Management, Lagos",
  "Nile University of Nigeria, Abuja",
  "Nnamdi Azikiwe University, Awka",
  "North Eastern University, Gombe",
  "Northwest University, Kano",
  "Northwest University, Sokoto",
  "Novena University, Ogume",
  "Obafemi Awolowo University, Ile-Ife",
  "Obong University, Obong Ntak",
  "Oduduwa University, Ipetumodu",
  "Ojaja University, Eiyenkorin",
  "Olabisi Onabanjo University, Ago-Iwoye",
  "Olusegun Agagu University of Science and Technology, Okitipupa",
  "Omega University, Kaduna",
  "Ondo State University of Medical Sciences",
  "Ondo State University of Science and Technology, Okitipupa",
  "Osun State University, Osogbo",
  "Owolabi University, Oke-Ila Orangun",
  "PAMO University of Medical Sciences, Port Harcourt",
  "Pan-Atlantic University, Lagos",
  "Paul University, Awka",
  "Peaceland University, Enugu",
  "Pearl University, Calabar",
  "Peter University, Achina-Onneh",
  "Philomath University, Kuje",
  "Phoenix University, Agwada",
  "Plateau State University, Bokkos",
  "Precious Cornerstone University, Ibadan",
  "Prime University, Kuje",
  "Prince Abubakar Audu University, Anyigba (Kogi State University)",
  "Rayhaan University, Kebbi",
  "Redeemer's University, Ede",
  "Regnum Medical University, Lagos",
  "Renaissance University, Enugu",
  "Rev. Fr. Moses Orshio Adasu University, Makurdi (formerly Benue State University)",
  "Rhema University, Aba",
  "Ritman University, Ikot Ekpene",
  "Rivers State University, Port Harcourt",
  "Saisa University of Medical Sciences and Technology, Sokoto",
  "Salem University, Lokoja",
  "Sam Maris University, Supare",
  "Samuel Adegboyega University, Ogwa",
  "Sani Bello University, Kontagora",
  "Shanahan University, Onitsha",
  "Shehu Shagari University of Education, Sokoto",
  "Skyline University Nigeria, Kano",
  "Sokoto State University, Sokoto",
  "Southern Atlantic University, Uyo",
  "Southwestern University, Okun-Owa",
  "Spiritan University, Nneochi",
  "Sports University, Idumuje-Ugboko",
  "State University of Medical and Applied Sciences, Igbo-Eno",
  "Sule Lamido University, Kafin Hausa",
  "Summit University, Offa",
  "Tai Solarin Federal University of Education, Ijagun",
  "Tai Solarin University of Education, Ijagun",
  "Tansian University, Umunya",
  "Taraba State University of Tropical Agriculture, Science, Technology and Climate Action, Gembu",
  "Taraba State University, Jalingo",
  "Tazkiyah University, Kaduna",
  "The Duke Medical University, Calabar",
  "Thomas Adewumi University, Oko-Irese",
  "Tonnie Iredia University of Communication, Benin City",
  "Topfaith University, Mkpatak",
  "Transatlantic University of Medicine and Health Sciences, Umuchukwu",
  "Trinity University, Ogun State",
  "Umaru Musa Yar'adua University, Katsina",
  "Ummah University of Nigeria, Abuja",
  "Unique Open University, Ojo",
  "University of Abuja",
  "University of Aeronautics and Aerospace Engineering, Ezza",
  "University of Africa, Toru-Orua",
  "University of Agriculture and Environmental Sciences, Umuagwo",
  "University of Benin",
  "University of Calabar",
  "University of Cross River State, Calabar",
  "University of Delta, Agbor",
  "University of Fortune, Igbotako",
  "University of Ibadan",
  "University of Ilesa, Osun State",
  "University of Ilorin",
  "University of Innovation, Science and Technology, Omuma",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Maritime Studies, Oron",
  "University of Medical Sciences, Ondo",
  "University of Mkar, Mkar",
  "University of Nigeria, Nsukka",
  "University of Offa, Offa",
  "University of Port Harcourt",
  "University of Uyo",
  "University on the Niger, Umunya",
  "Usmanu Danfodiyo University, Sokoto",
  "Venite University, Iloro-Ekiti",
  "Veritas University, Abuja",
  "Vision University, Ikogbo",
  "Wellspring University, Benin City",
  "Wesley University, Ondo",
  "West Midlands Open University, Ibadan",
  "Western Delta University, Oghara",
  "Westland University, Iwo",
  "Wigwe University, Isiokpo",
  "Yobe State University, Damaturu",
  "Yusuf Maitama Sule Federal University of Education, Kano",
  "Yusuf Maitama Sule University, Kano",
  "Zamfara State University, Talata Mafara",
] as const;

export function filterUniversities(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [...NIGERIAN_UNIVERSITIES];
  const starts: string[] = [];
  const contains: string[] = [];
  for (const name of NIGERIAN_UNIVERSITIES) {
    const n = name.toLowerCase();
    if (n.startsWith(q)) starts.push(name);
    else if (n.includes(q)) contains.push(name);
  }
  return [...starts, ...contains];
}
